src/Entity/Chassis.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use App\Entity;
use App\Entity\Product;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ChassisRepository")
 */
/** @ORM\Entity */
class Chassis extends Product
{

    /**
     * @return mixed
     */
    public function getChassisType()
    {
        return $this->chassisType;
    }

    /**
     * @param mixed $chassisType
     */
    public function setChassisType($chassisType): void
    {
        $this->chassisType = $chassisType;
    }

    /**
     * @return mixed
     */
    public function getGpuLength()
    {
        return $this->gpuLength;
    }

    /**
     * @param mixed $gpuLength
     */
    public function setGpuLength($gpuLength): void
    {
        $this->gpuLength = $gpuLength;
    }

    /**
     * @return mixed
     */
    public function getCoolerSupport()
    {
        return $this->cooler_support;
    }

    /**
     * @param mixed $cooler_support
     */
    public function setCoolerSupport($cooler_support): void
    {
        $this->cooler_support = $cooler_support;
    }
    /**
     * @ORM\Column(type="string", length=10)
     * @Assert\NotBlank()
     */
    private $chassisType;
    /**
     * @ORM\Column(type="integer", length=10)
     * @Assert\NotBlank()
     */
    private $gpuLength;
    /**
     * @ORM\Column(type="integer", length=10)
     * @Assert\NotBlank()
     */
    private $cooler_support;
}

templates/AdminArea/AddCustomer.html.twig
{% extends 'AdminArea/base.html.twig' %}
{% block body %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Add new customer</h1>
        </div>

    {% form_theme form 'bootstrap_4_layout.html.twig' %}
        {% if customer is defined %}
            {{ form_start(form) }}
            {{ form_row(form._token) }}
            {{ form_errors(form) }}

            Name {{ form_widget(form.name) }}
            Surname {{ form_widget(form.surname) }}
            Phone number {{ form_widget(form.phone_number) }}
            Email {{ form_widget(form.email) }}
            Address {{ form_widget(form.address) }}
            <div style="visibility: hidden;">{{ form_widget(form.id) }}</div>
            <button type="submit" class="btn btn-primary">Edit customer</button>
        {% else %}
            {{ form_start(form) }}
            {{ form_row(form._token) }}
            {{ form_errors(form) }}
            ID {{ form_widget(form.id) }}
            Name {{ form_widget(form.name) }}
            Surname {{ form_widget(form.surname) }}  
            Phone number {{ form_widget(form.phone_number) }}
            Email {{ form_widget(form.email) }}
            Address {{ form_widget(form.address) }}
            <br>
            <button type="submit" class="btn btn-primary">Add new customer</button>
        {% endif %}

{% endblock %}

templates/AdminArea/AddProduct.html.twig
{% extends 'AdminArea/base.html.twig' %}

{% block body %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Add new product</h1>
        </div>
        <div class="container">
            <form action="{{  'selected' }}">
                <div class="form-group">
                    <label for="exampleSelect1">Select Product type</label>
                    <select class="form-control" id="type" name="type">
                        <option value="MB">Motherboard</option>
                        <option value="RAM">Memory</option>
                        <option value="Storage">Storage</option>
                        <option value="CPU">Processor</option>
                        <option value="GPU">Video card</option>
                        <option value="PSU">Power supply</option>
                        <option value="Chassis">Case</option>
                        <option value="CPUCooler">Processor cooler</option>
                        <option value="ChassisCooler">Case cooler</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>

{% endblock %}

templates/AdminArea/AddProductCPUCooler.html.twig
{% extends 'AdminArea/base.html.twig' %}
{% block body %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Add new product</h1>
    </div>

    {% form_theme form 'bootstrap_4_layout.html.twig' %}
        {{ form_start(form) }}
        {{ form_row(form._token) }}
        {{ form_errors(form) }}
        Product Number {{ form_widget(form.product_number) }}
        Name {{ form_widget(form.name) }}
        Price {{ form_widget(form.price) }}
        Discount Price {{ form_widget(form.discount_price) }}
        Quantity {{ form_widget(form.quantity) }}
        Long Description {{ form_widget(form.long_description) }}
        Short Description {{ form_widget(form.short_description) }}
        Warranty Time {{ form_widget(form.warranty_time) }}
        RPM {{ form_widget(form.RPM) }}
        Noise level {{ form_widget(form.noiseLevel) }}
        Size {{ form_widget(form.size) }}
        Type {{ form_widget(form.CPUCoolerType) }}
        <br>
        <button type="submit" class="btn btn-primary">Add new product</button>

{% endblock %}

templates/AdminArea/AddProductChassisCooler.html.twig
{% extends 'AdminArea/base.html.twig' %}
{% block body %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Add new product</h1>
    </div>

    {% form_theme form 'bootstrap_4_layout.html.twig' %}
        {{ form_start(form) }}
        {{ form_row(form._token) }}
        {{ form_errors(form) }}
        Product Number {{ form_widget(form.product_number) }}
        Name {{ form_widget(form.name) }}
        Price {{ form_widget(form.price) }}
        Discount Price {{ form_widget(form.discount_price) }}
        Quantity {{ form_widget(form.quantity) }}
        Long Description {{ form_widget(form.long_description) }}
        Short Description {{ form_widget(form.short_description) }}
        Warranty Time {{ form_widget(form.warranty_time) }}
        Size {{ form_widget(form.size) }}
        RPM {{ form_widget(form.RPM) }}
        Airflow {{ form_widget(form.airflow) }}
        Noise Level {{ form_widget(form.noiseLevel) }}
        <br>
        <button type="submit" class="btn btn-primary">Add new product</button>

{% endblock %}

templates/AdminArea/AddProductMB.html.twig
{% extends 'AdminArea/base.html.twig' %}
{% block body %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Add new product</h1>
    </div>

    {% form_theme form 'bootstrap_4_layout.html.twig' %}
        {{ form_start(form) }}
        {{ form_row(form._token) }}
        {{ form_errors(form) }}
        Product Number {{ form_widget(form.product_number) }}
        Name {{ form_widget(form.name) }}
        Price {{ form_widget(form.price) }}
        Discount Price {{ form_widget(form.discount_price) }}
        Quantity {{ form_widget(form.quantity) }}
        Long Description {{ form_widget(form.long_description) }}
        Short Description {{ form_widget(form.short_description) }}
        Warranty Time {{ form_widget(form.warranty_time) }}
        CPU Socket {{ form_widget(form.cpuSocket) }}
        RAM Type {{ form_widget(form.ramType) }}
        Size {{ form_widget(form.size) }}
        Power Consumption {{ form_widget(form.powerConsumption) }}
        <br>
        <button type="submit" class="btn btn-primary">Add new product</button>

{% endblock %}

templates/AdminArea/AddProductRAM.html.twig
{% extends 'AdminArea/base.html.twig' %}
{% block body %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Add new product</h1>
    </div>

    {% form_theme form 'bootstrap_4_layout.html.twig' %}
        {{ form_start(form) }}
        {{ form_row(form._token) }}
        {{ form_errors(form) }}
        Product Number {{ form_widget(form.product_number) }}
        Name {{ form_widget(form.name) }}
        Price {{ form_widget(form.price) }}
        Discount Price {{ form_widget(form.discount_price) }}
        Quantity {{ form_widget(form.quantity) }}
        Long Description {{ form_widget(form.long_description) }}
        Short Description {{ form_widget(form.short_description) }}
        Warranty Time {{ form_widget(form.warranty_time) }}
        Type {{ form_widget(form.RAMtype) }}
        Speed {{ form_widget(form.speed) }}
        CAS {{ form_widget(form.CAS) }}
        <br>
        <button type="submit" class="btn btn-primary">Add new product</button>

{% endblock %}

templates/AdminArea/AddWorker.html.twig
{% extends 'AdminArea/base.html.twig' %}
{% block body %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Add new worker</h1>
        </div>

    {% form_theme form 'bootstrap_4_layout.html.twig' %}
        {% if worker is defined %}
            {{ form_start(form) }}
            {{ form_row(form._token) }}
            {{ form_errors(form) }}

            Name {{ form_widget(form.name) }}
            Surname {{ form_widget(form.surname) }}
            Birth date {{ form_widget(form.birth_date) }}
            Address {{ form_widget(form.address) }}
            Phone number {{ form_widget(form.phone_number) }}
            Email {{ form_widget(form.email) }}
            <div style="visibility: hidden;">{{ form_widget(form.duty) }}</div>
            <div style="visibility: hidden;">{{ form_widget(form.id) }}</div>
            <button type="submit" class="btn btn-primary">Edit worker</button>
        {% else %}
            {{ form_start(form) }}
            {{ form_row(form._token) }}
            {{ form_errors(form) }}
            Duty {{ form_widget(form.duty) }}
            ID {{ form_widget(form.id) }}
            Name {{ form_widget(form.name) }}
            Surname {{ form_widget(form.surname) }}
            Birth date {{ form_widget(form.birth_date) }}
            Address {{ form_widget(form.address) }}
            Phone number {{ form_widget(form.phone_number) }}
            Email {{ form_widget(form.email) }}
            <br>
            <button type="submit" class="btn btn-primary">Add new worker</button>
        {% endif %}

{% endblock %}

templates/AdminArea/CustomersOrderReport.html.twig
{% extends 'AdminArea/base.html.twig' %}
{% block body %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Orders report</h1>
    </div>
<div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th>#</th>
            <th>Header</th>
            <th>Header</th>
            <th>Header</th>
            <th>Header</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td>Uzsakymu</td>
            <td>ipsum</td>
            <td>dolor</td>
            <td>sit</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Uzsakymu</td>
            <td>consectetur</td>
            <td>adipiscing</td>
            <td>elit</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Uzsakymu</td>
            <td>nec</td>
            <td>odio</td>
            <td>Praesent</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Uzsakymu</td>
            <td>Sed</td>
            <td>cursus</td>
            <td>ante</td>
        </tr>
        <tr>
            <td>5</td>
            <td>Uzsakymu</td>
            <td>diam</td>
            <td>Sed</td>
            <td>nisi</td>
        </tr>     
        </tbody>
    </table>
</div>
{% endblock %}

templates/AdminArea/EditProduct.html.twig
{% extends 'AdminArea/base.html.twig' %}
{% block body %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Add new product</h1>
    </div>

    {% form_theme form 'bootstrap_4_layout.html.twig' %}
    {% if product is defined and mb is defined %}
        {{ form_start(form) }}
        {{ form_row(form._token) }}
        {{ form_errors(form) }}

        Name {{ form_widget(form.name) }}
        Price {{ form_widget(form.price) }}
        Discount Price {{ form_widget(form.discount_price) }}
        Quantity {{ form_widget(form.quantity) }}
        Long Description {{ form_widget(form.long_description) }}
        Short Description {{ form_widget(form.short_description) }}
        Warranty Time {{ form_widget(form.warranty_time) }}
        CPU Socket {{ form_widget(form.cpuSocket) }}
        RAM Type {{ form_widget(form.ramType) }}
        Size {{ form_widget(form.size) }}
        Power Consumption {{ form_widget(form.powerConsumption) }}
        <div style="visibility: hidden;">{{ form_widget(form.product_number) }}</div>
        <button type="submit" class="btn btn-primary">Edit product</button>
    {% endif %}
    {% if product is defined and cpu is defined %}
        {{ form_start(form) }}
        {{ form_row(form._token) }}
        {{ form_errors(form) }}

        Name {{ form_widget(form.name) }}
        Price {{ form_widget(form.price) }}
        Discount Price {{ form_widget(form.discount_price) }}
        Quantity {{ form_widget(form.quantity) }}
        Long Description {{ form_widget(form.long_description) }}
        Short Description {{ form_widget(form.short_description) }}
        Warranty Time {{ form_widget(form.warranty_time) }}
        Socket {{ form_widget(form.socket) }}
        Speed {{ form_widget(form.speed) }}
        Cores {{ form_widget(form.cores) }}
        Power Consumption {{ form_widget(form.powerConsumption) }}
        <div style="visibility: hidden;">{{ form_widget(form.product_number) }}</div>
        <button type="submit" class="btn btn-primary">Edit product</button>
    {% endif %}
    {% if product is defined and gpu is defined %}
        {{ form_start(form) }}
        {{ form_row(form._token) }}
        {{ form_errors(form) }}

        Name {{ form_widget(form.name) }}
        Price {{ form_widget(form.price) }}
        Discount Price {{ form_widget(form.discount_price) }}
        Quantity {{ form_widget(form.quantity) }}
        Long Description {{ form_widget(form.long_description) }}
        Short Description {{ form_widget(form.short_description) }}
        Warranty Time {{ form_widget(form.warranty_time) }}
        Memory {{ form_widget(form.memory) }}
        Core Clock {{ form_widget(form.coreClock) }}
        Memory type {{ form_widget(form.memoryType) }}
        Size {{ form_widget(form.size) }}
        Power Consumption {{ form_widget(form.powerConsumption) }}
        <div style="visibility: hidden;">{{ form_widget(form.product_number) }}</div>
        <button type="submit" class="btn btn-primary">Edit product</button>
    {% endif %}
    {% if product is defined and ram is defined %}
        {{ form_start(form) }}
        {{ form_row(form._token) }}
        {{ form_errors(form) }}

        Name {{ form_widget(form.name) }}
        Price {{ form_widget(form.price) }}
        Discount Price {{ form_widget(form.discount_price) }}
        Quantity {{ form_widget(form.quantity) }}
        Long Description {{ form_widget(form.long_description) }}
        Short Description {{ form_widget(form.short_description) }}
        Warranty Time {{ form_widget(form.warranty_time) }}
        Type {{ form_widget(form.RAMtype) }}
        Speed {{ form_widget(form.speed) }}
        CAS {{ form_widget(form.CAS) }}
        <div style="visibility: hidden;">{{ form_widget(form.product_number) }}</div>
        <button type="submit" class="btn btn-primary">Edit product</button>
    {% endif %}
    {% if product is defined and psu is defined %}
        {{ form_start(form) }}
        {{ form_row(form._token) }}
        {{ form_errors(form) }}

        Name {{ form_widget(form.name) }}
        Price {{ form_widget(form.price) }}
        Discount Price {{ form_widget(form.discount_price) }}
        Quantity {{ form_widget(form.quantity) }}
        Long Description {{ form_widget(form.long_description) }}
        Short Description {{ form_widget(form.short_description) }}
        Warranty Time {{ form_widget(form.warranty_time) }}
        Form {{ form_widget(form.form) }}
        Watts {{ form_widget(form.watts) }}
        Modular {{ form_widget(form.modular) }}
        <div style="visibility: hidden;">{{ form_widget(form.product_number) }}</div>
        <button type="submit" class="btn btn-primary">Edit product</button>
    {% endif %}
    {% if product is defined and storage is defined %}
        {{ form_start(form) }}
        {{ form_row(form._token) }}
        {{ form_errors(form) }}

        Name {{ form_widget(form.name) }}
        Price {{ form_widget(form.price) }}
        Discount Price {{ form_widget(form.discount_price) }}
        Quantity {{ form_widget(form.quantity) }}
        Long Description {{ form_widget(form.long_description) }}
        Short Description {{ form_widget(form.short_description) }}
        Warranty Time {{ form_widget(form.warranty_time) }}
        Size {{ form_widget(form.size) }}
        Type {{ form_widget(form.storageType) }}
        Form {{ form_widget(form.form) }}
        <div style="visibility: hidden;">{{ form_widget(form.product_number) }}</div>
        <button type="submit" class="btn btn-primary">Edit product</button>

    {% endif %}
    {% if product is defined and cpucooler is defined %}
        {{ form_start(form) }}
        {{ form_row(form._token) }}
        {{ form_errors(form) }}

        Name {{ form_widget(form.name) }}
        Price {{ form_widget(form.price) }}
        Discount Price {{ form_widget(form.discount_price) }}
        Quantity {{ form_widget(form.quantity) }}
        Long Description {{ form_widget(form.long_description) }}
        Short Description {{ form_widget(form.short_description) }}
        Warranty Time {{ form_widget(form.warranty_time) }}
        RPM {{ form_widget(form.RPM) }}
        Noise level {{ form_widget(form.noiseLevel) }}
        Size {{ form_widget(form.size) }}
        Type {{ form_widget(form.CPUCoolerType) }}
        <div style="visibility: hidden;">{{ form_widget(form.product_number) }}</div>
        <button type="submit" class="btn btn-primary">Edit product</button>

    {% endif %}
    {% if product is defined and case is defined %}
        {{ form_start(form) }}
        {{ form_row(form._token) }}
        {{ form_errors(form) }}

        Name {{ form_widget(form.name) }}
        Price {{ form_widget(form.price) }}
        Discount Price {{ form_widget(form.discount_price) }}
        Quantity {{ form_widget(form.quantity) }}
        Long Description {{ form_widget(form.long_description) }}
        Short Description {{ form_widget(form.short_description) }}
        Warranty Time {{ form_widget(form.warranty_time) }}
        Type {{ form_widget(form.chassisType) }}
        GPU Length {{ form_widget(form.gpuLength) }}
        Cooler Support {{ form_widget(form.coolerSupport) }}
        <div style="visibility: hidden;">{{ form_widget(form.product_number) }}</div>
        <button type="submit" class="btn btn-primary">Edit product</button>
    {% endif %}
    {% if product is defined and casecooler is defined %}
        {{ form_start(form) }}
        {{ form_row(form._token) }}
        {{ form_errors(form) }}

        Name {{ form_widget(form.name) }}
        Price {{ form_widget(form.price) }}
        Discount Price {{ form_widget(form.discount_price) }}
        Quantity {{ form_widget(form.quantity) }}
        Long Description {{ form_widget(form.long_description) }}
        Short Description {{ form_widget(form.short_description) }}
        Warranty Time {{ form_widget(form.warranty_time) }}
        Size {{ form_widget(form.size) }}
        RPM {{ form_widget(form.RPM) }}
        Airflow {{ form_widget(form.airflow) }}
        Noise Level {{ form_widget(form.noiseLevel) }}
        <div style="visibility: hidden;">{{ form_widget(form.product_number) }}</div>
        <button type="submit" class="btn btn-primary">Edit product</button>
    {% endif %}

{% endblock %}

templates/AdminArea/RemoveCustomer.html.twig
{% extends 'AdminArea/base.html.twig' %}
{% block body %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Remove customer</h1>
        </div>
        <form>
            <div class="form-group">
                <label for="exampleInputEmail1">Customer id or name</label>
                <input type="text" class="form-control" id="id" aria-describedby="customer_delete" placeholder="">
            </div>
            <button type="submit" class="btn btn-primary">Search</button>
        </form>
{% endblock %}

templates/AdminArea/RemoveProduct.html.twig
{% extends 'AdminArea/base.html.twig' %}
{% block body %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Remove product</h1>
        </div>
        <form>
            <div class="form-group">
                <label for="exampleInputEmail1">Product code or name</label>
                <input type="text" class="form-control" id="productCode" aria-describedby="product_delete" placeholder="">
            </div>
            <button type="submit" class="btn btn-primary">Search</button>
        </form>
{% endblock %}

templates/AdminArea/reports.html.twig
{% extends 'AdminArea/base.html.twig' %}
{% block body %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Reports</h1>
    </div>
    <button onclick="location.href='{{ path('ProductsReport') }}'" type="button" class="btn btn-primary">Products Report</button>
    <button onclick="location.href='{{ path('CustomersOrderReport') }}'" type="button" class="btn btn-primary">Customers Order Report</button>

{% endblock %}

templates/AdminArea/workers.html.twig
{% extends 'AdminArea/base.html.twig' %}
{% block body %}
    <div class="alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>ERROR</strong> {% if error is defined and error is not empty %}
        <div>  {{ error }} </div>
        {% endif %} }}
    </div>
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Workers</h1>
        </div>
        <button onclick="location.href='{{ path('AddWorker') }}'" type="button" class="btn btn-primary">Add new worker</button>
        <br>
        <br>
        <table class="table table-striped table-sm">
            <tr>
                <th>Duty</th>
                <th>ID</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Birth date</th>
                <th>Address</th>
                <th>Phone number</th>
                <th>Email</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
            {% for p in workers %}
            <tr>
                <td>{{ p.duty }}</td>
                <td>{{ p.id }}</td>
                <td>{{ p.name }}</td>
                <td>{{ p.surname }}</td>
                <td>{{ p.birthDate|date('Y-m-d') }}</td>
                <td>{{ p.address }}</td>
                <td>{{ p.phoneNumber }}</td>
                <td>{{ p.email }}</td>
                <td><button onclick="location.href='{{ '/admin/workers/edit/' ~ p.id }}'" type="button" class="btn btn-primary btn-sm"><i class="fa fa-pencil" aria-hidden="true"></i></button></td>
                <td><button onclick="location.href='{{ '/admin/workers/delete/' ~ p.id }}'" type="button" class="btn btn-secondary btn-sm"><i class="fa fa-trash" aria-hidden="true"></i></button></td>
         </tr>
         {% endfor %}
        </table>
{% endblock %}